// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"
)

type Foo struct {
	ID        int64
	Message   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID            string
	Email         string
	PasswordHash  string
	Name          string
	AvatarUrl     string
	Provider      string
	ProviderID    string
	EmailVerified bool
	Disabled      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
