-- +goose Up
CREATE TABLE IF NOT EXISTS foos(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    message TEXT NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME
);

-- +goose Down
DROP TABLE IF EXISTS foos;