// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: health.sql

package db

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT sqlite_version()
`

func (q *Queries) HealthCheck(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, healthCheck)
	var sqlite_version string
	err := row.Scan(&sqlite_version)
	return sqlite_version, err
}
