// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type AdminAuditLog struct {
	ID             int64
	AdminUserID    string
	AdminEmail     string
	TargetUserID   string
	Action         string
	Resource       string
	Method         string
	Path           string
	QueryParams    string
	RequestBody    string
	IpAddress      string
	UserAgent      string
	StatusCode     int64
	ResponseTimeMs int64
	Timestamp      interface{}
	RequestID      string
}

type Foo struct {
	ID        int64
	Message   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID            string
	LookupID      string
	Email         string
	PasswordHash  string
	Secret        string
	Name          string
	Role          string
	AvatarUrl     string
	Provider      string
	ProviderID    string
	EmailVerified bool
	Disabled      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
