// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id,
  lookup_id,
  email,
  password_hash,
  name,
  avatar_url,
  provider,
  provider_id,
  email_verified,
  created_at,
  updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, lookup_id, email, password_hash, secret, name, role, avatar_url, provider, provider_id, email_verified, disabled, created_at, updated_at
`

type CreateUserParams struct {
	ID            string
	LookupID      string
	Email         string
	PasswordHash  string
	Name          string
	AvatarUrl     string
	Provider      string
	ProviderID    string
	EmailVerified bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.LookupID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.AvatarUrl,
		arg.Provider,
		arg.ProviderID,
		arg.EmailVerified,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LookupID,
		&i.Email,
		&i.PasswordHash,
		&i.Secret,
		&i.Name,
		&i.Role,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.EmailVerified,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, lookup_id, email, password_hash, secret, name, role, avatar_url, provider, provider_id, email_verified, disabled, created_at, updated_at FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LookupID,
		&i.Email,
		&i.PasswordHash,
		&i.Secret,
		&i.Name,
		&i.Role,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.EmailVerified,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, lookup_id, email, password_hash, secret, name, role, avatar_url, provider, provider_id, email_verified, disabled, created_at, updated_at FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LookupID,
		&i.Email,
		&i.PasswordHash,
		&i.Secret,
		&i.Name,
		&i.Role,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.EmailVerified,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProviderID = `-- name: GetUserByProviderID :one
SELECT id, lookup_id, email, password_hash, secret, name, role, avatar_url, provider, provider_id, email_verified, disabled, created_at, updated_at FROM users
WHERE provider = ? AND provider_id = ?
`

type GetUserByProviderIDParams struct {
	Provider   string
	ProviderID string
}

func (q *Queries) GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByProviderID, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LookupID,
		&i.Email,
		&i.PasswordHash,
		&i.Secret,
		&i.Name,
		&i.Role,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.EmailVerified,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBylookupID = `-- name: GetUserBylookupID :one
SELECT id, lookup_id, email, password_hash, secret, name, role, avatar_url, provider, provider_id, email_verified, disabled, created_at, updated_at FROM users
WHERE lookup_id = ?
`

func (q *Queries) GetUserBylookupID(ctx context.Context, lookupID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBylookupID, lookupID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LookupID,
		&i.Email,
		&i.PasswordHash,
		&i.Secret,
		&i.Name,
		&i.Role,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.EmailVerified,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  email = ?,
  password_hash = ?,
  name = ?,
  avatar_url = ?,
  provider = ?,
  provider_id = ?,
  email_verified = ?,
  created_at = ?,
  updated_at = ?
WHERE id = ?
RETURNING id, lookup_id, email, password_hash, secret, name, role, avatar_url, provider, provider_id, email_verified, disabled, created_at, updated_at
`

type UpdateUserParams struct {
	Email         string
	PasswordHash  string
	Name          string
	AvatarUrl     string
	Provider      string
	ProviderID    string
	EmailVerified bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ID            string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.AvatarUrl,
		arg.Provider,
		arg.ProviderID,
		arg.EmailVerified,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LookupID,
		&i.Email,
		&i.PasswordHash,
		&i.Secret,
		&i.Name,
		&i.Role,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.EmailVerified,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSecret = `-- name: UpdateUserSecret :exec
UPDATE users SET secret = ? WHERE id = ?
`

type UpdateUserSecretParams struct {
	Secret string
	ID     string
}

// #nosec G101 this is a parameterized query, no hardcoded credential
func (q *Queries) UpdateUserSecret(ctx context.Context, arg UpdateUserSecretParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSecret, arg.Secret, arg.ID)
	return err
}
