
name: golangci-lint

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.2.1
          args: --timeout=3m --modules-download-mode=vendor
